#Prometheus configuration file
global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'python-metrics'
    static_configs:
      - targets: ['python-metrics:8000']



#Raspberry Pi Metrics (IP Address:port)
  - job_name: 'raspberry_pi_temps'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.1.10.71:9100']

  - job_name: 'raspberry-pi'
    static_configs:
      - targets: ['10.1.10.71:8000']

